[package]
name = "snake"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16"
bevy_aseprite_ultra = { version = "0.5.0", features = ["asset_processing"] }
log = "0.4.27"
env_logger = "0.11.8"
bevy-inspector-egui = "0.31.0"
